services:
    - docker
env:
    - DOCKER_COMPOSE_VERSION="1.25.4" SLEEP_TIME=300 PORT=8000 DOMAIN_NAME="my.web.666.com"

before_install:
    - sudo rm /usr/local/bin/docker-compose
    - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
    - chmod +x docker-compose 
    - sudo mv docker-compose /usr/local/bin
    - sudo apt-get update
    - sudo apt-get install -y python3 python3-pip curl
    - pip3 install requests
addons:
    hosts:
        - my.web.666.com

install:
    - sed -i 's/[0-9]*[1-9][0-9]*:80/'${PORT}':80/g' docker-compose.yml
    - docker-compose up -d
    - sleep ${SLEEP_TIME}

script:
    - sudo bash check_config.sh
    - sudo bash check_poc.sh
    - cat docker-compose.yml
    - sudo cat /etc/hosts
    - sudo cat ids/logs/notice.log
    - curl -vv -L http://${DOMAIN_NAME}:${PORT}
    - sudo bash del_shell_file.sh