version: '2'

services:
  mariadb:
      image: 'bitnami/mariadb:10.3'
      environment:
          - MARIADB_USER=bn_testlink
          - MARIADB_DATABASE=bitnami_testlink
          - ALLOW_EMPTY_PASSWORD=yes
      volumes:
          - 'mariadb_data:/bitnami'
  web:
      # image: 'bitnami/testlink:1.9.20-debian-10-r12'
      build:
         context: .
         dockerfile: Dockerfile_web
      environment:
          - MARIADB_HOST=mariadb
          - MARIADB_PORT_NUMBER=3306
          - TESTLINK_DATABASE_USER=bn_testlink
          - TESTLINK_DATABASE_NAME=bitnami_testlink
          - ALLOW_EMPTY_PASSWORD=yes
      ports:
          - '8001:80'
          - '443:443'
      volumes:
          - 'testlink_data:/bitnami'
          
      depends_on:
          - mariadb
      restart: always
      stdin_open: true
      tty: true 
      
  config:
     build:
       context: .
       dockerfile: Dockerfile_config
     environment: 
       - PYTHONIOENCODING=utf-8
     container_name: config-app
     depends_on:
       - web
<<<<<<< HEAD
=======
     volumes: 
      - ./config/:/opt/data/
>>>>>>> 4bbfa3c6f7172728365a0d3ea7cd33cef2648eff
       
  poc:
     build:
       context: .
       dockerfile: Dockerfile_poc
     container_name: poc-app
     depends_on:
       - web
       - config
     volumes: 
<<<<<<< HEAD
      - ./poc/:/opt/poc/
=======
       - ./poc/:/opt/poc/
>>>>>>> 4bbfa3c6f7172728365a0d3ea7cd33cef2648eff

volumes:
  mariadb_data:
    driver: local
  testlink_data:
    driver: local
