version: '3.1'

services:
  mariadb:
      image: 'bitnami/mariadb:10.3'
      container_name: testlink-db-app
      environment:
          - MARIADB_USER=bn_testlink
          - MARIADB_DATABASE=bitnami_testlink
          - ALLOW_EMPTY_PASSWORD=yes
      volumes:
          - 'mariadb_data:/bitnami'
      healthcheck:
            test: "/usr/bin/mysql --user=bn_testlink --password=bitnami --execute \"SHOW DATABASES;\""
            #test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 3
  web:
      build:
         context: ./web
         dockerfile: Dockerfile
      container_name: testlink-web-app
      environment:
          - MARIADB_HOST=mariadb
          - MARIADB_PORT_NUMBER=3306
          - TESTLINK_DATABASE_USER=bn_testlink
          - TESTLINK_DATABASE_NAME=bitnami_testlink
          - ALLOW_EMPTY_PASSWORD=yes
      ports:
          - '8000:80'
          - '443:443'
      volumes:
          - 'testlink_data:/bitnami'
      depends_on:
          - mariadb
      restart: always
      stdin_open: true
      tty: true 
      
  zeek:
    image: fixel/zeek:latest
    container_name: testlink-zeek
    network_mode: 'service:web'
    volumes:
      - ./ids/logs:/usr/local/zeek/logs
      - ./ids/policy_detect:/usr/local/zeek/share/zeek/policy/policy_detect
    command: -C -i eth0 policy/policy_detect  
    
  config:
     build:
       context: ./config
       dockerfile: Dockerfile
     environment: 
       - PYTHONIOENCODING=utf-8
     container_name: testlink-config-app
     depends_on:
       - web
     volumes: 
      - ./config/:/opt/data/
       
  poc:
     build:
       context: ./poc
       dockerfile: Dockerfile
     container_name: testlink-poc-app
     depends_on:
       - web
       - config
     volumes: 
       - ./poc/:/opt/poc/

volumes:
  mariadb_data:
    driver: local
  testlink_data:
    driver: local
