# This is a basic workflow to help you get started with Actions
name: Docker Image CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        image-name: [testlink_poc]
    steps:
      - uses: actions/checkout@v1
      - name: Components Security Scan - container scan
        run: docker build -t xxxxxxxxzhang/poc:1.0  -f ./Dockerfile_poc .
      - uses: anchore/scan-action@master
        with:
          image-reference: "xxxxxxxxzhang/poc:1.0"
          dockerfile-path: "./Dockerfile_poc"
          include-app-packages: true
          debug: true
