# This is a basic workflow to help you get started with Actions
name: Docker Image CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-18.04
     
    steps:
      - uses: actions/checkout@v2.0.0
      - name: Shell Check
        run: |
         pwd
         ls
         docker run --rm -v "$PWD:/mnt" koalaman/shellcheck:stable *.sh
      - name: Build Images And Backup
        id: buildAndPushImage
        uses: risfeng/docker-image-build-push-action@master
        with:
          docker_file: './web'
          registry_url: 'registry.cn-hangzhou.aliyuncs.com'
          namespaces: 'dve_images'
          repository_name: 'testlink_web' 
          user_name: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}
          image_version: 'v1'
          include-app-packages: true
          debug: true

      - name: Deploy DVE
        run: | 
          docker-compose up -d
          ls
          docker-compose logs poc

      - uses: actions/setup-node@v2.0.0
        with:
          node-version: '12'    
      - name: Check PoC Result
        run: bash check_poc.sh
      - uses: actions/setup-node@v2.0.0
        with:
          node-version: '12'
      - run: |
          npm install
          
      - name: Recognize Exploit Traffic
        run: |
         cat ids/logs/notice.log
         cp -f ids/logs/notice.log ci/traffic_backup/notice.log
         git add ci/traffic_backup/
         git config --local user.email "972844082@qq.com"
         git config --local user.name "xxxxxxxxzhang"
         git commit -m "CI push traffic back"

      - name: Check Service Availability
        run: |
          sleep 100
          npm init -f
          npm -v
          node -v
          npm i puppeteer
          node ci/check_availability.js
          git config --local user.email "972844082@qq.com"
          git config --local user.name "xxxxxxxxzhang"
          git add ci/screenshots/
          git commit -m "CI push sreenshots back"

      - name: Components Security Scan - container scan
        run: docker build -t xxxxxxxxzhang/web:1.0  -f ./web/Dockerfile .

      - uses: anchore/scan-action@v2.0.0
        with:
          image-reference: "xxxxxxxxzhang/web:1.0"
          dockerfile-path: "./web/Dockerfile"

      - name: Components Security Scan - anchore inline scan JSON results
        run: for j in `ls ./anchore-reports/*.json`; do echo "---- ${j} ----"; cat ${j}; echo; done

      - name: Components Security Scan - show vulnerabilities log in human readable format
        run: jq -r '.vulnerabilities[] | "\(.vuln)\t\(.severity)\t\(.package)\t\(.package_name)\t\(.package_version)"' ./anchore-reports/vulnerabilities.json | sort -k2 | grep -v Negligible
  
      - name: Push Screenshots And Traffic Back To Master
        uses: ad-m/github-push-action@master
        with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
