# This is a basic workflow to help you get started with Actions
name: Docker Image CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-18.04
     
    steps:
      - uses: actions/checkout@v1
      - name: Components Security Scan - container scan
        run: docker build -t xxxxxxxxzhang/web:1.0  -f ./Dockerfile_web .
      - uses: anchore/scan-action@master
        with:
          image-reference: "xxxxxxxxzhang/web:1.0"
          dockerfile-path: "./Dockerfile_web"

          include-app-packages: true
          debug: true

      - name: Deploy DVE
        run: | 
          docker-compose up -d
          ls
          docker-compose logs poc
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'    
      - name: Check PoC Result
        run: bash check_poc.sh
        
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - run: |
          npm install
          npm -v
      - name: Check PoC Result
        run: curl http://127.0.0.1:8000/
      - name: Check Service Availability
        run: |
          sleep 100
          npm init -f
          npm -v
          node -v
          npm i puppeteer
          node ci/check_availability.js
          git config --local user.email "972844082@qq.com"
          git config --local user.name "xxxxxxxxzhang"
          git add ci/screenshots/
          git commit -m "CI push sreenshots back"
          
      - name: Recognize Exploit Traffic
        run: |
         cat ids/logs/notice.log
         cp -f ids/logs/notice.log ci/traffic_backup/notice.log
         git config --local user.email "972844082@qq.com"
         git config --local user.name "xxxxxxxxzhang"
         git add ci/traffic_backup/
         git commit -m "CI push traffic back"
        

      - name: Components Security Scan - anchore inline scan JSON results
        run: for j in `ls ./anchore-reports/*.json`; do echo "---- ${j} ----"; cat ${j}; echo; done
      - name: Components Security Scan - show vulnerabilities log in human readable format
        run: jq -r '.vulnerabilities[] | "\(.vuln)\t\(.severity)\t\(.package)\t\(.package_name)\t\(.package_version)"' ./anchore-reports/vulnerabilities.json | sort -k2 | grep -v Negligible  
