# This is a basic workflow to help you get started with Actions
name: Docker Image CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-18.04
     
    steps:
      - uses: actions/checkout@v1
      - name: Components Security Scan - container scan
        run: docker build -t xxxxxxxxzhang/web:1.0  -f ./Dockerfile_web .
      - uses: anchore/scan-action@master
        with:
          image-reference: "xxxxxxxxzhang/web:1.0"
          dockerfile-path: "./Dockerfile_web"

          include-app-packages: true
          debug: true

      - name: Deploy DVE
        run: | 
          ls
          docker-compose up -d
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'

      - name: Components Security Scan - anchore inline scan JSON results
        run: for j in `ls ./anchore-reports/*.json`; do echo "---- ${j} ----"; cat ${j}; echo; done
      - name: Components Security Scan - show vulnerabilities log in human readable format
        run: jq -r '.vulnerabilities[] | "\(.vuln)\t\(.severity)\t\(.package)\t\(.package_name)\t\(.package_version)"' ./anchore-reports/vulnerabilities.json | sort -k2 | grep -v Negligible  
